# Generated by Django 3.0.7 on 2020-06-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_remove_snack_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
